### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by dungphanxuan** [vova07/yii2-start-comments-module#5]
Hello, when i run command php console/yii rbac/init and have error Unknow command "comment/rbac/add" . How can i solve problem!
Thanks

**Comment by vova07** [comment]
Hi @dungphanxuan ,
Do you run `php yii rbac/init` of my `Yii2-Start` application or it's another command?

**Comment by dungphanxuan** [comment]
Yes, my project base on Yii2 starter kit https://github.com/trntv/yii2-starter-kit.
I'm success run rbac/init. But run php yii comments/rbac/add not found.

Node. Trntv config console app on https://github.com/trntv/yii2-starter-kit/tree/master/console.

**Comment by vova07** [comment]
You may add `comment` module to your console config file:
```php
...
'modules' => [
    'comments' => [
        'class' => 'vova07\comments\Module',
        'controllerNamespace' => 'vova07\comments\commands'
    ]
]
...
```

**Comment by dungphanxuan** [comment]
Sucess. i just config 
'comments'=>[
            'class'=>'vova07\comments\commands\RbacController'
        ]
on yii2 statert kit console config. and run comments/add and it ok!
So how can you show me to config comment on each blog post!

**Comment by vova07** [comment]
> So how can you show me to config comment on each blog post!
Is it a question ?

**Comment by dungphanxuan** [comment]
ah, it some example to use comments module.

**Comment by vova07** [comment]
If I undertand you right, here is some demo code:
```php
// view.php
echo \vova07\comments\widgets\Comments::widget(
    [
        'model' => $model // $model is an instance or ActiveRecord
   ]
);
```
But before to use it you may add a new available for commenting instance via `backend` controller.

**Comment by dungphanxuan** [comment]
Hi thank, but i launcher router /comments/models/index/ in backend is'nt not found. How can i config or fix it. 
http://backend.yii2-starter-kit.dev/comments/models/index/

**Comment by vova07** [comment]
You need to configure it, in your backend config file too:
```php
'modules' => [
    'comments' => [
        'class' => 'vova07\comments\Module',
        'isBackend' => true
    ]
],
```

**Comment by dungphanxuan** [comment]
Hi, I follow you instruction and go to backend with access /comments but not found. 

My app base on trntv Yii2-Starter-kit.? thank

**Comment by vova07** [comment]
Do you add URL rules? Seems like there is the problem.
Configure your URL manager to can access the comment module.

**Comment by dungphanxuan** [comment]
Hi @vova07 . How can i config model class. I have successful created comment model in backend. 
My model is "common/models/Article". But i submit a comment then has error: 
"Model class is invalid"

$model is ActiveRecord and insctance of article item!
